version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    hostname: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
    networks:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin
#    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
#      MYSQL_ROOT_PASSWORD: my_root_password  # No need
      # We don't need PMA_USER & PMA_PASSWORD if we provide MYSQL_ROOT_PASSWORD. Otherwise we do.
#      PMA_USER: username
#      PMA_PASSWORD: password
    networks:
      - mysql
    depends_on:
      - mysql

networks:
  mysql:

volumes:
  mysql_data:
